name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - run: ./mvnw clean package --batch-mode --no-transfer-progress      
      - run: %JAVA_HOME%\bin\jpackage.exe @target\jpackage-win.args --type exe
        shell: cmd
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: target/distr/win/*.exe